/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Thai Thanh Nguyen
 */
import javax.swing.JOptionPane;

public class SW extends javax.swing.JFrame {

    /**
     * Creates new form SW
     */
    public SW() {
        initComponents();
        this.setSize(1000, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mnuPopUp = new javax.swing.JPopupMenu();
        mnuBackground = new javax.swing.JMenu();
        mnuRed = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuBlue = new javax.swing.JMenuItem();
        mnuForeground = new javax.swing.JMenu();
        mnuPink = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuYellow = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuClose = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQuit = new javax.swing.JMenuItem();
        mnuCustom = new javax.swing.JMenu();
        mnuCustom1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuCustom21 = new javax.swing.JRadioButtonMenuItem();
        mnuCustom22 = new javax.swing.JRadioButtonMenuItem();

        mnuBackground.setText("Background");

        mnuRed.setBackground(new java.awt.Color(255, 0, 0));
        mnuRed.setText("Red");
        mnuRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRedActionPerformed(evt);
            }
        });
        mnuBackground.add(mnuRed);
        mnuBackground.add(jSeparator3);

        mnuBlue.setBackground(new java.awt.Color(0, 0, 255));
        mnuBlue.setText("Blue");
        mnuBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBlueActionPerformed(evt);
            }
        });
        mnuBackground.add(mnuBlue);

        mnuPopUp.add(mnuBackground);

        mnuForeground.setText("Foreground");

        mnuPink.setForeground(new java.awt.Color(255, 0, 255));
        mnuPink.setText("Pink");
        mnuPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPinkActionPerformed(evt);
            }
        });
        mnuForeground.add(mnuPink);
        mnuForeground.add(jSeparator4);

        mnuYellow.setForeground(new java.awt.Color(255, 255, 0));
        mnuYellow.setText("Yellow");
        mnuYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuYellowActionPerformed(evt);
            }
        });
        mnuForeground.add(mnuYellow);

        mnuPopUp.add(mnuForeground);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txt1.setColumns(20);
        txt1.setRows(5);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 880, 510);

        mnuFile.setText("File");

        mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuOpen.setText("Open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuOpen);
        mnuFile.add(jSeparator1);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClose);
        mnuFile.add(jSeparator2);

        mnuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnuQuit.setText("Quit");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuQuit);

        jMenuBar1.add(mnuFile);

        mnuCustom.setText("Custom");

        mnuCustom1.setSelected(true);
        mnuCustom1.setText("Custom 1");
        mnuCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom1ActionPerformed(evt);
            }
        });
        mnuCustom.add(mnuCustom1);

        jMenu1.setText("Custom 2");

        buttonGroup1.add(mnuCustom21);
        mnuCustom21.setSelected(true);
        mnuCustom21.setText("Custom 21");
        mnuCustom21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom21ActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCustom21);

        buttonGroup1.add(mnuCustom22);
        mnuCustom22.setText("Custom 22");
        mnuCustom22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom22ActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCustom22);

        mnuCustom.add(jMenu1);

        jMenuBar1.add(mnuCustom);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Menu Open is clicked!");
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Menu Close is clicked!");
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom1ActionPerformed
        // TODO add your handling code here:
        if (mnuCustom1.isSelected()) {
            txt1.append("Hellooooo!\n");
        } else {
            txt1.append("Gudbye!!!!\n");
        }
    }//GEN-LAST:event_mnuCustom1ActionPerformed

    private void mnuCustom21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom21ActionPerformed
        // TODO add your handling code here:
        txt1.append("Mnu Custom 21, selected: " + mnuCustom21.isSelected() + "\n");
    }//GEN-LAST:event_mnuCustom21ActionPerformed

    private void mnuCustom22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom22ActionPerformed
        // TODO add your handling code here:
        txt1.append("Mnu Custom 22, selected: " + mnuCustom22.isSelected() + "\n");
    }//GEN-LAST:event_mnuCustom22ActionPerformed

    private void mnuRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRedActionPerformed
        // TODO add your handling code here:
        txt1.setBackground(mnuRed.getBackground());
    }//GEN-LAST:event_mnuRedActionPerformed

    private void mnuBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBlueActionPerformed
        // TODO add your handling code here:
        txt1.setBackground(mnuBlue.getBackground());
    }//GEN-LAST:event_mnuBlueActionPerformed

    private void txt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            mnuPopUp.show(txt1, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_txt1MouseReleased

    private void mnuPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPinkActionPerformed
        // TODO add your handling code here:
        txt1.setForeground(mnuPink.getForeground());
    }//GEN-LAST:event_mnuPinkActionPerformed

    private void mnuYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuYellowActionPerformed
        // TODO add your handling code here:
        txt1.setForeground(mnuYellow.getForeground());
    }//GEN-LAST:event_mnuYellowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnuBackground;
    private javax.swing.JMenuItem mnuBlue;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenu mnuCustom;
    private javax.swing.JCheckBoxMenuItem mnuCustom1;
    private javax.swing.JRadioButtonMenuItem mnuCustom21;
    private javax.swing.JRadioButtonMenuItem mnuCustom22;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuForeground;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuPink;
    private javax.swing.JPopupMenu mnuPopUp;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuRed;
    private javax.swing.JMenuItem mnuYellow;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
